export const apartments = [
  {
    id: 1,
    title: "Studio meublé Ngoa-Ekellé",
    location: "Ngoa-Ekellé, Yaoundé — 300m de l'UYI",
    price: 45000,
    rooms: 1,
    surface: 25,
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80",
    description: "Studio moderne et sécurisé à 300m de l'Université de Yaoundé I. Eau et électricité incluses. Idéal pour révisions au calme. Gardiennage 24h/24.",
    contact: "+237690123456",
    status: "Disponible",
    isCertified: true
  },
  {
    id: 2,
    title: "Chambre en colocation à SOA",
    location: "SOA, Yaoundé — Campus FASA/ENSP",
    price: 30000,
    rooms: 1,
    surface: 18,
    image: "https://images.unsplash.com/photo-1484154218962-a197022b5858?auto=format&fit=crop&w=800&q=80",
    description: "Chambre disponible dans une belle villa à SOA, à 5 min à pied des campus FASA et ENSP. 3 colocataires max. Cuisine équipée, Wi-Fi, groupe électrogène.",
    contact: "+237677654321",
    status: "Bon plan",
    isCertified: false
  },
  {
    id: 3,
    title: "Appartement 2 pièces Ekié",
    location: "Ekié, Yaoundé — Près de l'UYI",
    price: 65000,
    rooms: 2,
    surface: 45,
    image: "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=800&q=80",
    description: "Bel appartement 2 pièces dans le quartier Ekié, proche du campus de l'Université de Yaoundé I. Sécurité 24h, eau courante, parking disponible.",
    contact: "+237655789012",
    status: "Populaire",
    isCertified: true
  },
  {
    id: 4,
    title: "Studio à KEYCE Academy Douala",
    location: "Bonamoussadi, Douala — KEYCE",
    price: 50000,
    rooms: 1,
    surface: 22,
    image: "https://images.unsplash.com/photo-1502672023488-70e25813eb80?auto=format&fit=crop&w=800&q=80",
    description: "Studio entièrement meublé à Bonamoussadi, à 5 minutes de KEYCE Academy. Climatisation, Wi-Fi fibre optique, sécurité résidence. Pas de coupure d'eau.",
    contact: "+237699234567",
    status: "Disponible",
    isCertified: true
  },
  {
    id: 5,
    title: "Appartement meublé Ngousso",
    location: "Ngousso, Yaoundé — Proche de l'ENAM",
    price: 70000,
    rooms: 2,
    surface: 50,
    image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=800&q=80",
    description: "Grand appartement 2 chambres à Ngousso, idéal pour 2 étudiants. Proche de l'ENAM, de la Cité Verte et du marché. Groupe électrogène, eau de forage.",
    contact: "+237677345678",
    status: "Disponible",
    isCertified: false
  },
  {
    id: 6,
    title: "Chambre VIP Bastos-Obili",
    location: "Obili, Yaoundé — Proche UYII / 2iE",
    price: 40000,
    rooms: 1,
    surface: 20,
    image: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80",
    description: "Chambre VIP très bien équipée à Obili, à 10min à pied de l'Université de Yaoundé II et de 2iE. Cuisine partagée, Wi-Fi haut débit, voisinage calme.",
    contact: "+237655456789",
    status: "Dernière chambre",
    isCertified: true
  },
  {
    id: 7,
    title: "Mini-villa Campus Molyko Buea",
    location: "Molyko, Buea — Université de Buea",
    price: 55000,
    rooms: 2,
    surface: 40,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80",
    description: "Appartement moderne à Molyko, à 2 minutes de l'Université de Buea. Idéal pour étudiants anglophones. Internet stable, eau permanente, sécurité résidence.",
    contact: "+237699567890",
    status: "Disponible",
    isCertified: true
  },
  {
    id: 8,
    title: "Studio Bonamoussadi — IUC",
    location: "Bonamoussadi, Douala — IUC",
    price: 48000,
    rooms: 1,
    surface: 28,
    image: "https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?auto=format&fit=crop&w=800&q=80",
    description: "Studio proche de l'IUC (Institut Universitaire de la Côte) à Bonamoussadi. Résidence sécurisée, climatisé, Wi-Fi inclus. Quartier animé, toutes commodités à proximité.",
    contact: "+237677678901",
    status: "Bon plan",
    isCertified: false
  }
];
